num1=float(input('Pick a number'))
num2=float(input('Pick another number'))
s=(num1+num2)
#print('The sum of',num1,'and',num2,'is {}'.format(s))
print('The sum of {} and {} is {}'.format(num1,num2,s))