raz = int(input('Digite a razão da sua PA'))
prim = int(input('Digite o primeiro termo da sua PA'))
pa = 0
qnt = 1
recebe = 1
while recebe != 0:
    total = recebe +10
    while qnt != total:
        pa = (prim)+raz*qnt
        qnt = qnt + 1
        print(pa,end='')
        print(' > ',end='')
        recebe = int(input('Quantos valores deseja ver a mais?'))